export const RUNTIME_CONSTANTS = Object.freeze({
  GLOBAL_URGENCY_MIN: 0.3,
  DEDUPLICATION_SIMILARITY: 0.85,
  SPEAKER_IN_FLOW_PAUSE_MS: 500,
  SPEAKER_IN_FLOW_WINDOW_MS: 10000,
  
  // New: Attention Gate
  SPEAKING_TIMEOUT_MS: 30000,           // Max 30 seconds per agent speech
  THRESHOLD_INCREASE_STEP: 0.05,        // FR-805
  THRESHOLD_DECREASE_STEP: 0.02,        // FR-806
  
  // New: Arbitration Policy
  AGENT_COOLDOWN_MS: 60000,
  SIMILARITY_NOVELTY_THRESHOLD: 0.85,
  IN_FLOW_THRESHOLD_MULTIPLIER: 1.5,
  MAX_HISTORY: 50,
  MIN_INTERRUPT_COST: 0.1,
  SPEAKER_IN_FLOW_COST: 1.5,
  RECENT_INTERRUPTION_COST: 0.3,
  EMOTIONAL_INTENSITY_COST: 0.8,
  CONVERGENCE_BONUS_MULTIPLIER: 0.15,
  MAX_CONVERGENCE_BONUS: 0.45,
});
