export enum EventType {
  SPEAKER_STARTED = 'speaker.started',
  SPEAKER_STOPPED = 'speaker.stopped',
  TRANSCRIPT_UPDATE = 'transcript.update',
  PAUSE_DETECTED = 'pause.detected',
  DELTA_PRODUCED = 'delta.produced',
  CYCLE_STARTED = 'cycle.started',
  CYCLE_COMPLETED = 'cycle.completed',
  INTERRUPT_GRANTED = 'interrupt.granted',
  AGENT_SPEAKING = 'agent.speaking',
  AGENT_FINISHED = 'agent.finished',
  BLACKBOARD_UPDATED = 'blackboard.updated',
  CONTEXT_UPDATED = 'context.updated',
  MEETING_STARTED = 'meeting.started',
  TOPIC_CHANGED = 'topic.changed',
}
